---
  - name: Installing Prometheus in Ubuntu
    apt:
      name: prometheus
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Installing Snapd in CentOS
    dnf:
      name:
        - snapd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Enable Snapd in CentOS
    tags: snapd,centos
    command: systemctl enable --now snapd.socket
    when: ansible_distribution == "CentOS"

  - name: Installing Prometheus in CentOS
    command: snap install prometheus --classic
    when: ansible_distribution == "CentOS"
